gulp/tasks/buildCustomJs.js
Currently syntax error cause babel to break. We want to prevent this.
=> prevent babel from breaking

gulp/tasks/createPackage.js
Fixes #3 
Explicitly including the view code directory in the source
files that get added to the zip file output. Without this,
the Primo Back Office complains that the zip file
"must have a root directory with the name of the view code" and
fails to load the package.
=> Fix the create-package gulp task

gulp/primoProxy.js
Fixes #17 
When a CENTRAL_PACKAGE is uploaded to Primo, the bootstrapping
process loads the centralCustom module from the package's
custom.js file. This fix ensures that the same behavior occurs
in the local server proxy by setting the `customJs` property
on the customization object when the `run` task is executed.
=> Fix run task: load the centralCustom module

gulp/browserSyncManager.js, gulp/tasks/servers.js
Use browsersync.stream() to watch and stream update the custom CSS file
(custom1.css).
Side note: naming in `config.js` isn't very intuitive! Why is `*.css` called "main path", while "custom1.css" is called "path", for instance? And why mix "view" and "custom" as prefix?
- viewCssDir: primo-explore/custom/${view}/css
- customCssMainPath: primo-explore/custom/${view}/css/*.css
- customCssPath: primo-explore/custom/${view}/css/custom1.css
There's also lots of duplication, only some of the functions make use of other functions.
=> Add browsersync for custom css

gulp/tasks/build-scss.js
Fixes #24
According to the instructions, the colors.json file should
exist in the views directory root, but this task is actually
reading from the project root dir because gulp automatically
performs a cwd to the gulpfile.js location.
This fix makes the task behavior consistent with the README,
which is presumably ideal.
=> Fix the app-css task

gulp/config.js, gulp/tasks/images.js, gulp/tasks/servers.js, package.json
adds a gulp task to watch for png images in the `img` folder of installed npm modules, move them to the `img` folder of the working package, and reload the browser when images are changed.
this way npm modules that require their own images to add functionality to primo (for example, [primo-explore-resource-icons](https://www.npmjs.com/package/primo-explore-resource-icons)) will have the needed images added to the package automatically.
=> enable copying images from npm packages

gulp/config.js, gulp/tasks/buildCustomHtmlTemplates.js, gulp/tasks/buildCustomJs.js, package.json
I do not like to include HTML files inside my JS files. 
With this pull-request I can save my files in the ```myView/html/templates``` directory. The files will be compiled into a ```customTemplates.js``` file. This ```$templateCache```  can be referenced with a  ```templateUrl``` from within your component
ex. ```myView/html/templates/myFile.html``` can be referenced using ```templateUrl: 'myFile.html' ``` 
```js
app.component('prmSomeComponentAfter', {
bindings: {
parentCtrl: '<'
},
templateUrl: 'myFile.html',
controller: function() {
// your code here
}
});
```
=> Custom html templates

gulp/tasks/buildCustomJs.js
Changes the js build process as follows:
- Recursively watch the `js` directory for changes.
- Enable `debug` mode on the Browserify build. This option tells
Browserify to create source maps from `custom.js`, which are
*much* easier to read and debug:
=> Improve handling of multiple js files

gulp/tasks/buildCustomJs.js, package.json
```javascript
import myHTML from './myPage.html'
class MyController{
constructor(){
console.log('Hello World');
}
}
export let myConfig = {
bindings: {parentCtrl: '<'}
template: myHTML,
controller: MyController
}
```
Imports feel more natural in ES6(browserify).
=> allow to import HTML in ES6

gulp/config.js, gulp/tasks/build-scss.js, gulp/tasks/servers.js, gulpfile.js
This gives the possibility to use SCSS in the view package. 
The scss declarations must be located in a file called `main.scss` which is located in a folder called `/scss` in the root directory of the view package.
It is possible to put all scss declarations directly in the `main.scss` file or to use `@import` statement to reference other scss files containing scss declarations.
In order to enable the usage of SCSS the gulp run command has to be executed with the `--useScss` parameter: `gulp run --view [viewName] --useScss`
**Workflow**
(1) In addition to the CSS and JS watcher, new watchers are registered for all *.scss files in the new `/[viewName]/scss` folder.
(2) The scss declarations in the *.scss files are compiled to CSS and saved to `/[viewName]/css/custom-scss-compiled.css`
(3) …
=> Allow usage of SCSS in view package in order to create custom CSS

gulp/config.js
The distributed `config.js` should not include the `PROXY_SERVER` of a specific Primo instance.
=> Reset PROXY_SERVER to example value

gulp/config.js, gulp/tasks/buildCustomHtmlTemplates.js
I'd like to be able to include HTML templates from npm modules. With this pull-request, you can save html templates in an `html` directory within an npm module.
For example, `node_modules/package-name/html/myFile.html` can be referenced using `templateUrl: 'package-name/html/myFile.html'`
This builds on #46 Custom HTML Templates.
=> Support custom HTML templates from npm

gulp/tasks/buildCustomJs.js, package.json
This substantially reduces the size of the custom.js file.
A source map is available when running locally.
=> Minify/uglify JavaScript in the browserify build

gulp/config.js, gulp/tasks/buildCustomJs.js
this is a minor edit that supports adding customization module code installed through npm that resides in a `dist/` folder.
**use case**: i write primo customizations using a folder structure where the "compiled" angular module for a customization is output to a `dist/` folder (as distinct from `src/` - [example](https://github.com/alliance-pcsg/primo-explore-report-problem). it's easiest to install just this file, so i `.npmignore` all of my source code and other parts of the repo, so that ideally the only thing really installed from `npm` is the customization itself. the dev env doesn't pick up js located in the `dist/` folder yet because it doesn't look for that path.
it seems like a fairly established best practice to separate source code from built code in npm packages, and i think …
=> add dist/*.js files from node_modules when building by concatenation

gulp/tasks/build-scss.js, gulp/tasks/buildCustomCss.js, gulp/tasks/buildCustomHtmlTemplates.js, gulp/tasks/buildCustomJs.js, gulp/tasks/buildJsFromPrimoNodeModules.js, gulp/tasks/createPackage.js, gulp/tasks/servers.js
We wanted to be able to run `gulp create-package` without worrying about which view was last run or when it was run. This PR updates the gulp commands to build the custom code before the package is created. 
As a nice side-effect, this also adds the prompt for which view to use to `gulp run`, meaning `--view` is no longer necessary (but still available). It also adds the `--view` flag to `gulp create-package` so these two commands are now callable either way.
As a side note, this is my first foray into gulp tasks, and I had some difficulty getting the dependencies to wait for the view selection task, so if anyone has suggestions on a better way please speak up!
=> Build custom code before packaging

gulp/config.js, gulp/primoProxy.js, gulpfile.js
Fixes #83 
Proxied requests to primoExploreLogin will not work for SAML
authentication (server returns a 500 error). This change adds an
optional `--saml` parameter to the gulp run task. Setting the `--saml`
parameter instructs the local proxy server to redirect (vs proxy)
any primoExploreLogin requests to the target host. When SAML
authentication is complete, Primo will redirect the browser back
to localhost.
=> Redirect SAML login requests

README.md
Being new to primo development I didn't understand what was being communicated about the custom.js and custom1.css being overwritten until a more experienced primo developer explained the file concatenation. This PR is an attempt to clarify the feature's functionality in the README
=> Suggestion on wording

.gitignore, primo-explore/custom/.gitignore, primo-explore/tmp/.gitignore
- I'm currently trying to automate the running and testing of our primo views and addons with circleci and cypress.
- I'm using the `primo-explore-devenv` [npm package](https://www.npmjs.com/package/primo-explore-devenv) to grab the code for this 
- to run a view, you have to copy over the view directory into `primo-explore/custom/`, but that directory doesn't appear in the `npm` package (reasoning below)
- it's easy to just remake it with two `mkdir` commands, but it's initially confusing and unnecessary
- this PR has the effect of making the `npm` package better reflect the git repo (ensures that the `primo-explore/custom` and `primo-explore/tmp` directories show up)
- it _does not have any effect_ on what is or is not ignored _by git_ (doesn't affect the git ignore logic )
- it only …
=> unhide 'primo-explore/custom' and 'tmp/' directories from npm package

gulp/tasks/02-custom-js.js, gulp/tasks/03-scss.js, gulp/tasks/04-custom-css.js, gulp/tasks/09-images.js
hi @noamamit92 , many thanks for recent updates and merge my pull request.
i tried to rebuild my primo-explore-devenv docker image and ran into a few issues.
- the last parameter for gulp.watch should be a function and not ["custom-scss"] or ['custom-img'], so i changed this to gulp.series().
- when using --useScss parameter without scss/main.scss devenv fails, therefore i added {allowEmpty:true}
- it seems there is a problem for gulp.watch on files inside docker container, devenv does not stop to bulild custom.js, event though there are no file changes.  i found a suggestion on google and added  {interval: 1000, usePolling: true},  that makes it work again for me inside docker.
please review, thx
=> gulp.watch changes and docker

gulp/tasks/01-custom-html-templates.js
This works around a problem introduced by gulp 4 / vinyl 2 where `gulp-angular-template-cache` adds a leading slash to filenames, causing the URL to be read as an absolute path.
miickel/gulp-angular-templatecache#153
=> Add fix for relative pathnames in html templates

gulp/tasks/01-custom-html-templates.js, gulp/tasks/02-custom-js.js, gulp/tasks/07-primo-node-modules.js
gulp4 fix makes the reinstall-primo-node-modules, delete-primo-node-modules and install-primo-node-modules work again.
=> fix node-modules tasks, use gulp4-run-sequence and add callback

gulp/tasks/03-scss.js, package.json
This patch should fix the following autoprefixer warning when running gulp `app-css` task.
```
Creating network "primo-explore-vbk_default" with the default driver
[05:36:30] Using gulpfile /app/primo-explore-devenv/gulpfile.js
[05:36:30] Starting 'app-css'...
[05:36:30] Starting 'extract-scss-files'...
https://search.vbk.ac.at:443/primo-explore/lib/scsss.tar.gz
[05:36:30] Finished 'extract-scss-files' after 336 ms
[05:36:30] Starting 'color-variables'...
[05:36:30] Finished 'color-variables' after 38 ms
[05:36:30] Starting 'compile-scss'...
Replace Autoprefixer browsers option to Browserslist config.
Use browserslist key in package.json or .browserslistrc file.
Using browsers option can cause errors. Browserslist config 
can be used for Babel, Autoprefixer, postcss-normalize and other …
```
=> fix autoprefixer browsers option and replace by browserslist in package.json
